[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
bollard = "0.19.3"
futures-util = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
tar = "0.4.44"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["rt", "time"] }
walkdir = "2.5.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
