[package]
name = "graphql-common"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", default-features = false, features = ["macros"] }
async-graphql = { version = "7.2.1" }
paste = "1.0.15"

# log
tracing = "0.1.44"
