[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Thrift
thrift = { path = "../../common/thrift" }
volo = "0.12.2"
volo-thrift = "0.12.2"
tokio = { version = "1.49.0", features = ["full"] }

# jwt
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
serde = { version = "1.0.228", features = ["derive"] }

# log
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

# errors
anyhow = { version = "1.0.102", features = [] }
