[package]
name = "gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
http = "1.4.0"
rand = "0.10.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[target.'cfg(not(windows))'.dependencies]
pingora = { version = "0.7", features = ["proxy", "rustls"] }
